package emartPojo;
// Generated Jan 18, 2020 9:22:07 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/*
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "emart")
public class Cart implements java.io.Serializable {

	private Integer oid;
	private Product product;
	private int quantity;
	private Customer customer;
	private int amount;
	private boolean points; 
	
	public Cart() {
	}

	public Cart(Customer customer, Product product, int quantity, int amount,boolean points) {
		this.customer = customer;
		this.product = product;
		this.quantity = quantity;
		this.amount = amount;
		this.points = points;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "oid", unique = true, nullable = false)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
	
	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "custid")
	public Customer getCustomer() {
		return customer;
	}
	
	
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public boolean isPoints() {
		return points;
	}

	public void setPoints(boolean points) {
		this.points = points;
	}
	
}