package emartPojo;
// Generated Jan 18, 2020 9:22:07 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catsubcat generated by hbm2java
 */
@Entity
@Table(name = "catsubcat", catalog = "emart")
public class Catsubcat implements java.io.Serializable {

	private Integer cid;
	private Integer catid;
	private String name;
	private boolean flag;
	private String img;

	public Catsubcat() {
	}

	public Catsubcat(String name, boolean flag) {
		this.name = name;
		this.flag = flag;
	}

	public Catsubcat(Integer catid, String name, boolean flag, String img) {
		this.catid = catid;
		this.name = name;
		this.flag = flag;
		this.img = img;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@Column(name = "catid")
	public Integer getCatid() {
		return this.catid;
	}

	public void setCatid(Integer catid) {
		this.catid = catid;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isFlag() {
		return flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	public String getImg() {
		return img;
	}

	public void setImg(String img) {
		this.img = img;
	}

}
