package emartPojo;
// Generated Jan 18, 2020 9:22:07 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.*;

/*
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "emart", uniqueConstraints = @UniqueConstraint(columnNames = { "email", "mobno" }))
public class Customer implements java.io.Serializable {

	private Integer custid;
	private String cname;
	private String email;
	private String mobno;
	private int age;
	private String gender;
	private String password;
	private String address;
	private String address1;
	private boolean primemember;
	private int points;

	public Customer() {
	}

	public Customer(String cname, String email, String mobno, int age, String gender, String password, String address,
			boolean primemember, int points) {
		this.cname = cname;
		this.email = email;
		this.mobno = mobno;
		this.age = age;
		this.gender = gender;
		this.password = password;
		this.address = address;
		this.primemember = primemember;
		this.points = points;
	}

	public Customer(String cname, String email, String mobno, int age, String gender, String password, String address,
			String address1, boolean primemember, int points) {
		this.cname = cname;
		this.email = email;
		this.mobno = mobno;
		this.age = age;
		this.gender = gender;
		this.password = password;
		this.address = address;
		this.address1 = address1;
		this.primemember = primemember;
		this.points = points;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "custid", unique = true, nullable = false)
	public Integer getCustid() {
		return this.custid;
	}

	public void setCustid(Integer custid) {
		this.custid = custid;
	}

	@Column(name = "cname", nullable = false, length = 20)
	@NotEmpty(message="name can not be empty")
	@Pattern(regexp = "^[a-zA-Z]+$", message = "name must contain characters")
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "email", nullable = false, length = 30)
	@NotNull(message="Email Address is compulsory")
    @NotBlank(message="Email Address is compulsory")
    @Email(message = "Email Address is not a valid format")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobno", nullable = false, length = 15)
	public String getMobno() {
		return this.mobno;
	}

	public void setMobno(String mobno) {
		this.mobno = mobno;
	}
	
	@Column(name = "age", nullable = false)
	@Min(value = 18, message = "Age must be greater than or equal to 18")
	@Max(value = 150, message = "Age must be less than or equal to 150")
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "gender", nullable = false, length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "password", nullable = false, length = 20)
	@NotNull
	@Size(max = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "address1", length = 250)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "primemember", nullable = false)
	public boolean isPrimemember() {
		return this.primemember;
	}

	public void setPrimemember(boolean primemember) {
		this.primemember = primemember;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

}