package emartPojo;
// Generated Jan 18, 2020 9:22:07 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "emart")
public class Product implements java.io.Serializable {

	private Integer id;
	private Catsubcat catsubcat;
	private String name;
	private String pdetail;
	private int points;
	private int price;
	private int primeprice;
	private String image;
	private String modelno;
	private Float cgst;
	private Float sgst;
	private boolean promotional;

	public Product() {
	}

	public Product(Catsubcat catsubcat, String name, int points, int price, int primeprice) {
		this.catsubcat = catsubcat;
		this.name = name;
		this.points = points;
		this.price = price;
		this.primeprice = primeprice;
	}

	public Product(Catsubcat catsubcat, String name, String pdetail, int points, int price, int primeprice,
			String image, String modelno, Float cgst, Float sgst,boolean promotional) {
		this.catsubcat = catsubcat;
		this.name = name;
		this.pdetail = pdetail;
		this.points = points;
		this.price = price;
		this.primeprice = primeprice;
		this.image = image;
		this.modelno = modelno;
		this.cgst = cgst;
		this.sgst = sgst;
		this.promotional = promotional;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "cid", nullable = false)
	public Catsubcat getCatsubcat() {
		return this.catsubcat;
	}

	public void setCatsubcat(Catsubcat catsubcat) {
		this.catsubcat = catsubcat;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pdetail", length = 250)
	public String getPdetail() {
		return this.pdetail;
	}

	public void setPdetail(String pdetail) {
		this.pdetail = pdetail;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = 100;
	}

	@Column(name = "price", nullable = false, precision = 10, scale = 0)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "primeprice", nullable = false, precision = 10, scale = 0)
	public int getPrimeprice() {
		return this.primeprice;
	}

	public void setPrimeprice(int primeprice) {
		this.primeprice = primeprice;
	}

	@Column(name = "image", length = 30)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "modelno", length = 20)
	public String getModelno() {
		return this.modelno;
	}

	public void setModelno(String modelno) {
		this.modelno = modelno;
	}

	@Column(name = "cgst", precision = 12, scale = 0)
	public Float getCgst() {
		return this.cgst;
	}

	public void setCgst(Float cgst) {
		this.cgst = cgst;
	}

	@Column(name = "sgst", precision = 12, scale = 0)
	public Float getSgst() {
		return this.sgst;
	}

	public void setSgst(Float sgst) {
		this.sgst = sgst;
	}
	
	public boolean isPromotional() {
		return promotional;
	}

	public void setPromotional(boolean promotional) {
		this.promotional = promotional;
	}

	@Override
	public String toString() {
		return "Product [id=" + id + ", catsubcat=" + catsubcat + ", name=" + name + ", pdetail=" + pdetail
				+ ", points=" + points + ", price=" + price + ", primeprice=" + primeprice + ", image=" + image
				+ ", modelno=" + modelno + ", cgst=" + cgst + ", sgst=" + sgst + "]";
	}
}
